// import {Product} from "@/types/product";
import {Remark} from "@/types/remark";
//
// export const products: Product[] = [
//     {
//         id: 1,
//         title: "Classic Denim Jacket",
//         subtitle: "UrbanEdge Jacket",
//         price: 79.99,
//         discountPrice: 69.99,
//         rating: 4.5,
//         remark: "Trending",
//         stock: 0,
//         description: "A stylish denim jacket by UrbanEdge, perfect for layering all year round.",
//         color: ["Blue", "Black"],
//         size: ["S", "M", "L", "XL"],
//         category: "Outerwear",
//         brand: "UrbanEdge",
//         type: "Jacket",
//         sku: "SKU-1001",
//         barcode: "1234567890123",
//         images: ["/images/product/product1.png", "/images/product/product2.png"]
//     },
//     {
//         id: 2,
//         title: "Basic Crew Neck T-Shirt",
//         subtitle: "CottonCo T-Shirt",
//         price: 19.99,
//         rating: 4.2,
//         remark: "Features",
//         stock: 120,
//         description: "A soft and breathable crew neck t-shirt by CottonCo, ideal for everyday wear.",
//         color: ["White", "Gray"],
//         size: ["XS", "S", "M", "L"],
//         category: "Tops",
//         brand: "CottonCo",
//         type: "T-Shirt",
//         sku: "SKU-1002",
//         barcode: "2345678901234",
//         images: ["/images/product/product4.png", "/images/product/product1.png"]
//     },
//     {
//         id: 3,
//         title: "High-Waisted Skinny Jeans",
//         subtitle: "DenimX Jeans",
//         price: 59.99,
//         discountPrice: 49.99,
//         rating: 4.4,
//         remark: "New Arrival",
//         stock: 78,
//         description: "Flattering high-waisted skinny jeans by DenimX, perfect with any top.",
//         color: ["Dark Blue", "Black"],
//         size: ["S", "M", "L", "XL"],
//         category: "Bottoms",
//         brand: "DenimX",
//         type: "Jeans",
//         sku: "SKU-1003",
//         barcode: "3456789012345",
//         images: ["/images/product/product7.png", "/images/product/product2.png"]
//     },
//     {
//         id: 4,
//         title: "Men’s Chino Shorts",
//         subtitle: "CoolWear Shorts",
//         price: 34.99,
//         rating: 4.0,
//         remark: "Trending",
//         stock: 66,
//         description: "Comfortable chino shorts forms CoolWear, great for warm weather.",
//         color: ["Khaki", "Navy"],
//         size: ["M", "L", "XL"],
//         category: "Bottoms",
//         brand: "CoolWear",
//         type: "Shorts",
//         sku: "SKU-1004",
//         barcode: "4567890123456",
//         images: ["/images/product/product10.png", "/images/product/product13.png"]
//     },
//     {
//         id: 5,
//         title: "Floral Print Summer Dress",
//         subtitle: "Blossom Dress",
//         price: 49.99,
//         discountPrice: 39.99,
//         rating: 4.6,
//         remark: "New Arrival",
//         stock: 32,
//         description: "A lightweight floral summer dress by Blossom, made for sunny days.",
//         color: ["Pink", "White"],
//         size: ["S", "M", "L"],
//         category: "Dresses",
//         brand: "Blossom",
//         type: "Dress",
//         sku: "SKU-1005",
//         barcode: "5678901234567",
//         images: ["/images/product/product13.png", "/images/product/product16.png"]
//     },
//     {
//         id: 6,
//         title: "Zip-Up Hoodie",
//         subtitle: "HeatWave Hoodie",
//         price: 39.99,
//         rating: 4.3,
//         remark: "Features",
//         stock: 85,
//         description: "Cozy zip-up hoodie by HeatWave with soft fleece lining.",
//         color: ["Gray", "Black"],
//         size: ["M", "L", "XL", "XXL"],
//         category: "Outerwear",
//         brand: "HeatWave",
//         type: "Hoodie",
//         sku: "SKU-1006",
//         barcode: "6789012345678",
//         images: ["/images/product/product16.png", "/images/product/product1.png"]
//     },
//     {
//         id: 7,
//         title: "Striped Cotton Shirt",
//         subtitle: "SoftWear Shirt",
//         price: 29.99,
//         rating: 4.1,
//         remark: "Trending",
//         stock: 40,
//         description: "Classic striped cotton shirt by SoftWear, perfect for both casual and formal looks.",
//         color: ["White", "Blue"],
//         size: ["S", "M", "L", "XL"],
//         category: "Tops",
//         brand: "SoftWear",
//         type: "Shirt",
//         sku: "SKU-1007",
//         barcode: "7890123456789",
//         images: ["/images/product/product1.png", "/images/product/product7.png",]
//     },
//     {
//         id: 8,
//         title: "Slim Fit Blazer",
//         subtitle: "Layered Blazer",
//         price: 89.99,
//         discountPrice: 74.99,
//         rating: 4.7,
//         remark: "Features",
//         stock: 22,
//         description: "Tailored slim fit blazer by Layered for a modern professional look.",
//         color: ["Black", "Navy"],
//         size: ["M", "L", "XL"],
//         category: "Outerwear",
//         brand: "Layered",
//         type: "Blazer",
//         sku: "SKU-1008",
//         barcode: "8901234567890",
//         images: ["/images/product/product2.png", "/images/product/product13.png",]
//     },
//     {
//         id: 9,
//         title: "Athletic Joggers",
//         subtitle: "FitFlex Joggers",
//         price: 44.99,
//         rating: 4.5,
//         remark: "Trending",
//         stock: 58,
//         description: "Comfortable and breathable joggers forms FitFlex for workouts or lounging.",
//         color: ["Gray", "Black"],
//         size: ["S", "M", "L", "XL"],
//         category: "Bottoms",
//         brand: "FitFlex",
//         type: "Joggers",
//         sku: "SKU-1009",
//         barcode: "9012345678901",
//         images: ["/images/product/product4.png", "/images/product/product11.png",]
//     },
//     {
//         id: 10,
//         title: "Ribbed Knit Sweater",
//         subtitle: "CozyWear Sweater",
//         price: 54.99,
//         discountPrice: 44.99,
//         rating: 4.6,
//         remark: "New Arrival",
//         stock: 37,
//         description: "Warm ribbed knit sweater forms CozyWear with a soft touch.",
//         color: ["Beige", "Maroon"],
//         size: ["S", "M", "L"],
//         category: "Tops",
//         brand: "CozyWear",
//         type: "Sweater",
//         sku: "SKU-1010",
//         barcode: "1122334455667",
//         images: ["/images/product/product7.png", "/images/product/product8.png"]
//     },
//     {
//         id: 11,
//         title: "Cargo Pants",
//         subtitle: "UrbanEdge Pants",
//         price: 49.99,
//         rating: 4.4,
//         remark: "Features",
//         stock: 52,
//         description: "Multi-pocket cargo pants by UrbanEdge, durable and stylish.",
//         color: ["Olive", "Black"],
//         size: ["M", "L", "XL"],
//         category: "Bottoms",
//         brand: "UrbanEdge",
//         type: "Pants",
//         sku: "SKU-1011",
//         barcode: "2233445566778",
//         images: ["/images/product/product8.png", "/images/product/product1.png"]
//     },
//     {
//         id: 12,
//         title: "Leather Belt",
//         subtitle: "BuckleUp Belt",
//         price: 24.99,
//         rating: 4.3,
//         stock: 70,
//         remark: "Features",
//         description: "Durable leather belt with stylish buckle forms BuckleUp.",
//         color: ["Brown", "Black"],
//         size: ["M", "L", "XL"],
//         category: "Accessories",
//         brand: "BuckleUp",
//         type: "Belt",
//         sku: "SKU-1012",
//         barcode: "3344556677889",
//         images: ["/images/product/product10.png"]
//     },
//     {
//         id: 13,
//         title: "Running Sneakers",
//         subtitle: "Speedster Shoes",
//         price: 79.99,
//         rating: 4.5,
//         stock: 60,
//         remark: "New Arrival",
//         description: "Lightweight running sneakers with breathable mesh by Speedster.",
//         color: ["White", "Black"],
//         size: ["40", "41", "42", "43"],
//         category: "Footwear",
//         brand: "Speedster",
//         type: "Sneakers",
//         sku: "SKU-1013",
//         barcode: "4455667788990",
//         images: ["/images/product/product11.png", "/images/product/product1.png"]
//     },
//     {
//         id: 14,
//         title: "Wool Scarf",
//         subtitle: "CozyWrap Scarf",
//         price: 19.99,
//         rating: 4.2,
//         stock: 90,
//         remark: "Features",
//         description: "Soft wool scarf by CozyWrap, perfect for chilly evenings.",
//         color: ["Gray", "Red"],
//         size: ["One Size"],
//         category: "Accessories",
//         brand: "CozyWrap",
//         type: "Scarf",
//         sku: "SKU-1014",
//         barcode: "5566778899001",
//         images: ["/images/product/product13.png", "/images/product/product1.png"]
//     },
//     {
//         id: 15,
//         title: "Casual Polo Shirt",
//         subtitle: "SmartFit Polo",
//         price: 34.99,
//         rating: 4.1,
//         remark: "Trending",
//         stock: 75,
//         description: "Casual polo shirt by SmartFit for a clean, everyday look.",
//         color: ["Navy", "White"],
//         size: ["M", "L", "XL"],
//         category: "Tops",
//         brand: "SmartFit",
//         type: "Polo",
//         sku: "SKU-1015",
//         barcode: "6677889900112",
//         images: ["/images/product/product15.png", "/images/product/product1.png"]
//     },
//     {
//         id: 16,
//         title: "Classic Leather Boots",
//         subtitle: "TrailWear Boots",
//         price: 119.99,
//         rating: 4.6,
//         stock: 34,
//         remark: "Features",
//         description: "Durable leather boots by TrailWear, ideal for hiking and casual wear.",
//         color: ["Brown", "Black"],
//         size: ["41", "42", "43", "44"],
//         category: "Footwear",
//         brand: "TrailWear",
//         type: "Boots",
//         sku: "SKU-1016",
//         barcode: "7788990011223",
//         images: ["/images/product/product1.png", "/images/product/product8.png"]
//     },
//     {
//         id: 17,
//         title: "Knitted Beanie",
//         subtitle: "WarmHead Beanie",
//         price: 14.99,
//         rating: 4.0,
//         remark: "Trending",
//         stock: 120,
//         description: "Knitted beanie by WarmHead to keep you cozy during winter.",
//         color: ["Black", "Gray"],
//         size: ["One Size"],
//         category: "Accessories",
//         brand: "WarmHead",
//         type: "Beanie",
//         sku: "SKU-1017",
//         barcode: "8899001122334",
//         images: ["/images/product/product16.png", "/images/product/product1.png"]
//     },
//     {
//         id: 18,
//         title: "Sleeveless Tank Top",
//         subtitle: "ActiveFlex Tank",
//         price: 17.99,
//         rating: 4.2,
//         stock: 85,
//         remark: "Features",
//         description: "Breathable sleeveless tank for workouts by ActiveFlex.",
//         color: ["Black", "White"],
//         size: ["S", "M", "L"],
//         category: "Tops",
//         brand: "ActiveFlex",
//         type: "Tank",
//         sku: "SKU-1018",
//         barcode: "9900112233445",
//         images: ["/images/product/product13.png", "/images/product/product1.png"]
//     },
//     {
//         id: 19,
//         title: "Pleated Skirt",
//         subtitle: "ChicWear Skirt",
//         price: 39.99,
//         rating: 4.3,
//         stock: 42,
//         remark: "Features",
//         description: "Trendy pleated skirt by ChicWear, perfect for casual and formal outings.",
//         color: ["Black", "Beige"],
//         size: ["S", "M", "L"],
//         category: "Bottoms",
//         brand: "ChicWear",
//         type: "Skirt",
//         sku: "SKU-1019",
//         barcode: "1011121314156",
//         images: ["/images/product/product1.png", "/images/product/product13.png"]
//     },
//     {
//         id: 20,
//         title: "Sports Cap",
//         subtitle: "FlexFit Cap",
//         price: 12.99,
//         rating: 4.1,
//         stock: 110,
//         remark: "Trending",
//         description: "Lightweight and adjustable sports cap by FlexFit.",
//         color: ["Black", "Blue"],
//         size: ["One Size"],
//         category: "Accessories",
//         brand: "FlexFit",
//         type: "Cap",
//         sku: "SKU-1020",
//         barcode: "1213141516178",
//         images: ["/images/product/product2.png", "/images/product/product16.png"]
//     },
//     {
//         id: 21,
//         title: "Graphic Tee",
//         subtitle: "StreetArt T-Shirt",
//         price: 22.99,
//         rating: 4.0,
//         stock: 98,
//         remark: "Trending",
//         description: "Trendy graphic t-shirt with bold street-style design.",
//         color: ["Black", "White"],
//         size: ["S", "M", "L", "XL"],
//         category: "Tops",
//         brand: "StreetArt",
//         type: "T-Shirt",
//         sku: "SKU-1021",
//         barcode: "1314151617189",
//         images: ["/images/product/product4.png", "/images/product/product1.png"]
//     },
//     {
//         id: 22,
//         title: "Denim Skirt",
//         subtitle: "DenimX Skirt",
//         price: 44.99,
//         rating: 4.3,
//         stock: 54,
//         remark: "Trending",
//         description: "Stylish denim skirt by DenimX for a chic urban look.",
//         color: ["Blue"],
//         size: ["S", "M", "L"],
//         category: "Bottoms",
//         brand: "DenimX",
//         type: "Skirt",
//         sku: "SKU-1022",
//         barcode: "1415161718190",
//         images: ["/images/product/product7.png", "/images/product/product1.png"]
//     },
//     {
//         id: 23,
//         title: "Formal Leather Shoes",
//         subtitle: "ElegantStep Shoes",
//         price: 99.99,
//         rating: 4.5,
//         remark: "New Arrival",
//         stock: 38,
//         description: "Classic formal leather shoes by ElegantStep, perfect for work or events.",
//         color: ["Black", "Brown"],
//         size: ["40", "41", "42", "43"],
//         category: "Footwear",
//         brand: "ElegantStep",
//         type: "Shoes",
//         sku: "SKU-1023",
//         barcode: "1516171819201",
//         images: ["/images/product/product10.png", "/images/product/product1.png"]
//     },
//     {
//         id: 24,
//         title: "Cotton Shorts",
//         subtitle: "Breeze Shorts",
//         price: 29.99,
//         rating: 4.1,
//         remark: "New Arrival",
//         stock: 65,
//         description: "Light cotton shorts by Breeze, great for hot days.",
//         color: ["Gray", "Navy"],
//         size: ["M", "L", "XL"],
//         category: "Bottoms",
//         brand: "Breeze",
//         type: "Shorts",
//         sku: "SKU-1024",
//         barcode: "1617181920212",
//         images: ["/images/product/product10.png", "/images/product/product1.png"]
//     },
//     {
//         id: 25,
//         title: "Casual Hoodie",
//         subtitle: "DailyWear Hoodie",
//         price: 45.99,
//         rating: 4.4,
//         stock: 80,
//         remark: "Features",
//         description: "Comfortable casual hoodie by DailyWear for everyday use.",
//         color: ["Black", "Gray"],
//         size: ["M", "L", "XL"],
//         category: "Outerwear",
//         brand: "DailyWear",
//         type: "Hoodie",
//         sku: "SKU-1025",
//         barcode: "1718192021223",
//         images: ["/images/product/product11.png", "/images/product/product1.png"]
//     },
//     {
//         id: 26,
//         title: "Linen Shirt",
//         subtitle: "FreshWear Shirt",
//         price: 39.99,
//         rating: 4.2,
//         remark: "Trending",
//         stock: 55,
//         description: "Lightweight linen shirt for a fresh summer look.",
//         color: ["White", "Light Blue"],
//         size: ["M", "L", "XL"],
//         category: "Tops",
//         brand: "FreshWear",
//         type: "Shirt",
//         sku: "SKU-1026",
//         barcode: "1819202122234",
//         images: ["/images/product/product13.png", "/images/product/product1.png"]
//     },
//     {
//         id: 27,
//         title: "Maxi Dress",
//         subtitle: "GlamWear Dress",
//         price: 69.99,
//         rating: 4.5,
//         remark: "New Arrival",
//         stock: 25,
//         description: "Elegant maxi dress by GlamWear for special occasions.",
//         color: ["Red", "Blue"],
//         size: ["S", "M", "L"],
//         category: "Dresses",
//         brand: "GlamWear",
//         type: "Dress",
//         sku: "SKU-1027",
//         barcode: "1920212223245",
//         images: ["/images/product/product15.png", "/images/product/product1.png"]
//     }]
//
//
//
export const remarkList:Remark[] = [
    {
        id: 1,
        name: "New Arrival",
    },
    {
        id: 2,
        name: "Trending",
    },
    {
        id: 3,
        name: "Features",
    }
]
