#!/usr/bin/env node
/**
 * Generates TypeScript types from the backend's OpenAPI spec.
 *
 * Resolves the backend origin from env (BACKEND_ORIGIN first, then
 * NEXT_PUBLIC_BACKEND_URL), fetches <origin>/api-docs.json and writes
 * openapi-typescript output to src/lib/api/types.ts.
 */
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

// Project root = three levels up from src/lib/api/generate.mjs
const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");

// Prefer a locally saved copy of the spec (e.g. when the backend is not
// reachable from this environment) over a remote fetch.
const localSpec =
  process.env.BACKEND_OPENAPI_JSON ||
  resolve(rootDir, "openapi-dashboard.json");

const origin =
  process.env.BACKEND_ORIGIN || process.env.NEXT_PUBLIC_BACKEND_URL;

let specUrl;
let spec;

if (existsSync(localSpec)) {
  specUrl = `file://${localSpec}`;
  console.log(`Reading OpenAPI spec from ${specUrl} ...`);
  spec = JSON.parse(readFileSync(localSpec, "utf8"));
} else if (origin && !origin.startsWith("/")) {
  specUrl = `${origin.replace(/\/$/, "")}/api-docs.json`;
  console.log(`Fetching OpenAPI spec from ${specUrl} ...`);
  try {
    const res = await fetch(specUrl);
    if (!res.ok) {
      throw new Error(`HTTP ${res.status} ${res.statusText}`);
    }
    spec = await res.json();
  } catch (err) {
    console.error(`Failed to fetch ${specUrl}: ${err.message}`);
    process.exit(1);
  }
} else {
  console.error(
    "Error: no local spec (openapi-dashboard.json) and no reachable origin " +
      "(set BACKEND_ORIGIN or NEXT_PUBLIC_BACKEND_URL)."
  );
  process.exit(1);
}

const outputPath = resolve(rootDir, "src/lib/api/types.ts");

console.log("Generating types ...");
const types = await openapiTS(spec, {
  exportType: true,
  commentHeader: `/* eslint-disable */\n/* auto-generated by scripts/generate-api.mjs from ${specUrl} */`,
});

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, astToString(types));
console.log(`Wrote ${outputPath}`);
